#+TITLE: Walkthrough

This document walks through the process of creating a 3D model of a watershed, as well as printing it in one of Duke's 3D printers.

Current Requirements:
- *USGS HUC10 watershed* ID for watershed of interest
- *Google Earth Engine* Code Editor Access (application necessary, but usually applications are accepted instantly)
- *meshlab* software
- *QGIS* software
  - and QGIS plugin, *DEMto3D*

* Step 1: Google Earth Engine
If you don't already have access, sign up at [[https://signup.earthengine.google.com/#!/][Google Earth Engine's website.]] Once you have access, open up the [[https://code.earthengine.google.com/][GEE code editor]]. Now, copy all of the contents of the script from this repo, located at **~/GEE/watershed_dem.js** and paste it into a new script in the code editor. Once it is pasted, click **RUN**. Your watershed should, maybe after a little bit of time (0-2 minutes), appear on the map where it supposed to be, with a black and white elevation raster image clipped to the watershed outline. The **Tasks** tab in the right pane of the code editor should also, after a little time, be orange- click this tab. Here, you should see a task called watershed_elevation, next to a button that says **run**. CLick this. You may have to wait a little while, depending on the size of your watershed. If you stuck with a HUC10, it should run in roughly 2-8 minutes, but mileage may vary. When it is done, the task will report itself as complete. At this point, you should have a file of the same name, watershed_elevation, in your google drive- download this file, and, go to the QGIS section of this walkthrough.

* Step 2: QGIS
